import {instrument} from './scale-data.js';
import {STORAGE_KEY,PAGE_SIZE,freshState,restoreState,isComplete,scoreInstrument,pageComplete,event} from './core.mjs';
const $=id=>document.getElementById(id),legacyKey='traveler-lab-session-v1';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storageOK=true,raw=null,initialLang='zh';
try{raw=sessionStorage.getItem(STORAGE_KEY);try{initialLang=JSON.parse(sessionStorage.getItem(legacyKey)||'{}').lang==='en'?'en':'zh'}catch{}sessionStorage.removeItem(legacyKey)}catch{storageOK=false}
let state=raw?restoreState(raw,instrument):freshState(initialLang);state.instrumentId=instrument.id;
let timerStart=null,modalKind=null,modalReturn=null;
const t=(zh,en)=>state.lang==='zh'?zh:en,tr=obj=>obj?.[state.lang]||'';
const types={
 E:{image:'./assets/travelers/story.jpg',alt:{"zh":"旅人在古城巷弄中與當地人分享旅途故事。","en":"A traveler shares a spontaneous encounter in an old-town street."},icon:'☀',name:{zh:'故事旅人',en:'The Story Traveler'},line:{zh:'把相遇放進行囊，讓故事跟著你走。',en:'Pack a new encounter. Let a story come along.'}},
 A:{image:'./assets/travelers/companion.jpg',alt:{"zh":"兩位同行旅人在山間一起欣賞遼闊風景。","en":"Two companions enjoy a broad mountain view together."},icon:'♡',name:{zh:'同行旅人',en:'The Companion Traveler'},line:{zh:'一段風景，和人一起收藏。',en:'A view to collect with a companion.'}},
 C:{image:'./assets/travelers/route.jpg',alt:{"zh":"旅人攤開地圖，規劃通往遠方的旅行路線。","en":"A traveler studies an open map and plans the route ahead."},icon:'↗',name:{zh:'路線旅人',en:'The Route Traveler'},line:{zh:'把靈感畫成路線，為旅程留一張小地圖。',en:'Turn a spark into a route. Keep a little map for the journey.'}},
 ES:{image:'./assets/travelers/slow.jpg',alt:{"zh":"旅人在湖畔咖啡座放慢腳步，靜靜欣賞風景。","en":"A traveler slows down at a lakeside cafe and takes in the scenery."},icon:'≈',name:{zh:'慢步旅人',en:'The Unhurried Traveler'},line:{zh:'慢一點，讓風景有時間走進心裡。',en:'Slow down. Give the scenery a little time.'}},
 O:{image:'./assets/travelers/inspiration.jpg',alt:{"zh":"旅人在海岸小徑發現意想不到的景色與靈感。","en":"A traveler discovers unexpected scenery along a coastal path."},icon:'✦',name:{zh:'靈感旅人',en:'The Inspiration Traveler'},line:{zh:'地圖外的一點新奇，也是一段故事的開始。',en:'A surprise off the map can start a new story.'}}
};
const stageNames=()=>[t('開始體驗','Welcome'),t('探索風格','Explore'),t('旅行問卷','Questionnaire'),t('旅人故事卡','Story card'),t('揭露與回顧','Reveal & review')];
function save(){try{sessionStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch{storageOK=false}}
function log(type,detail={}){event(state,type,detail);save()}
function flushTimer(){if(timerStart!==null){const now=performance.now();state.consentMs+=Math.max(0,now-timerStart);timerStart=now;save()}}
function syncTimer(){if(state.step===2&&state.permissionOpen&&!document.hidden){if(timerStart===null)timerStart=performance.now()}else{flushTimer();timerStart=null}}
function rememberNavigation(push=false){history[push?'pushState':'replaceState']({lab:true,generation:state.startedAt,step:state.step,page:state.quizPage},'',location.href)}
function go(step){if(step===state.step||step>3&&!isComplete(state.answers,instrument))return;if(modalKind)closeModal();flushTimer();state.step=step;state.permissionOpen=false;syncTimer();log('stage',{stage:step});rememberNavigation(true);render(true)}
function clearSession(){if(modalKind)closeModal();flushTimer();timerStart=null;const lang=state.lang;try{sessionStorage.removeItem(STORAGE_KEY);sessionStorage.removeItem(legacyKey)}catch{}state=freshState(lang);state.instrumentId=instrument.id;save();rememberNavigation();render(true);$('status').textContent=t('本次答案、授權與操作紀錄已清除。','Answers, permissions and activity records for this session have been cleared.')}
function btn(id,zh,en,kind=''){return `<button class="button ${kind}" id="${id}">${esc(t(zh,en))}</button>`}
function render(focus=false){
 document.documentElement.lang=state.lang==='zh'?'zh-Hant':'en';document.title=t('旅人風格體驗','Traveler Style Experience');
 $('skip').textContent=t('跳至主要內容','Skip to main content');$('brand-name').innerHTML=`${esc(t('旅人風格體驗','Traveler Style'))}<small>FIND YOUR NEXT STORY</small>`;
 $('exit').textContent=t('退出並清除','Exit & clear');$('exit').hidden=state.step===1;$('reset').hidden=state.step===1;
 $('lang-zh').setAttribute('aria-pressed',state.lang==='zh');$('lang-en').setAttribute('aria-pressed',state.lang==='en');
 $('progress').setAttribute('aria-label',t('五階段進度','Five-stage progress'));
 $('progress').innerHTML=stageNames().map((s,i)=>`<div class="stage ${state.step===i+1?'active':state.step>i+1?'done':''}" ${state.step===i+1?'aria-current="step"':''}><span class="num">${state.step>i+1?'✓':i+1}</span><span>${esc(s)}</span></div>`).join('');
 $('privacy-foot').textContent=t('本次分頁保存','Saved in this tab');$('sources-button').hidden=state.step!==5;$('sources-button').textContent=t('量表來源、許可與計分','Instrument sources, permission & scoring');$('reset').textContent=t('重新開始並清除','Restart & clear');$('modal-close').textContent=t('關閉並返回','Close & return');
 $('main').innerHTML=(!storageOK?`<p class="error" role="status">${esc(t('瀏覽器無法保存本次資料；仍可作答，但刷新可能失去進度。','This browser cannot save session data. You can continue, but a refresh may lose progress.'))}</p>`:'')+[null,welcome,advert,quiz,result,reveal][state.step]();
 bindStep();document.querySelectorAll('[data-score-width]').forEach(el=>el.style.width=el.dataset.scoreWidth+'%');if(modalKind)renderModal();
 if(focus){$('main').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}
}
function welcome(){return `<section class="hero welcome-short"><div><span class="eyebrow">${esc(t('課堂模擬練習','CLASSROOM SIMULATION'))}</span><h1>${esc(t('出發前，先知道這一件事。','Before you go, one thing to know.'))}</h1><p class="lead">${esc(t('這是課程模擬練習，不會連接你的真實社群帳號；後續畫面與互動皆為模擬。','This is a classroom simulation. It will not connect to your real social accounts; all following screens and interactions are simulated.'))}</p><p class="muted">${esc(t('作答只保存在本次瀏覽器分頁。','Your responses stay in this browser tab.'))}</p><div class="actions">${btn('start','我已了解，開始體驗 →','I understand. Start the experience →')}</div></div><div class="hero-illustration" aria-hidden="true"><div class="route-circle"></div><span class="compass">↗</span><span class="stamp">YOUR NEXT STORY</span></div></section>`}
function travelerImage(c,result=false){return '<img class="'+(result?'traveler-image':'type-image')+'" src="'+esc(c.image)+'" alt="'+esc(tr(c.alt))+'" width="1536" height="1024" loading="'+(result?'eager':'lazy')+'" decoding="async">'}
function advert(){return `<section class="hero"><div><span class="eyebrow">TRAVELER STYLE / ${esc(t('下一段旅程，從你開始','YOUR NEXT JOURNEY STARTS WITH YOU'))}</span><h1>${esc(t('你的下一段旅程，\n會是哪一種故事？','What story will your next journey tell?')).replaceAll('\n','<br>')}</h1><p class="lead">${esc(t('10 個小問題，解鎖一張專屬旅人故事卡。五種旅人，你是哪一種呢?','10 quick questions. One traveler story card. Five traveler types—which one are you?'))}</p><div class="actions">${btn('begin-quiz','找到我的旅人故事 →','Find my traveler story →')}</div><p class="muted">${esc(t('10 題 · 約 2 分鐘 · 中英可切換','10 questions · About 2 minutes · Chinese / English'))}</p></div><div class="hero-illustration" aria-hidden="true"><span class="float-label">A LITTLE DETOUR. A NEW STORY.</span><div class="route-circle"></div><span class="compass">✦</span><span class="stamp">FIVE TRAVELER STORIES</span></div></section><div class="type-grid">${Object.values(types).map(c=>`<article class="type-card">${travelerImage(c)}<span class="type-icon" aria-hidden="true">${c.icon}</span><h2>${esc(tr(c.name))}</h2><p>${esc(tr(c.line))}</p></article>`).join('')}</div>`}
function permissionText(){return {answers:{title:t('本次回答','Answers in this session'),desc:t('用於本次旅人故事卡。','For your traveler story card.')},likes:{title:t('按讚紀錄','Like history'),desc:t('旅行照片、咖啡、博物館（示範資料）。','Travel photos, coffee, museums (example data).')},friends:{title:t('好友名單','Friend list'),desc:t('好友 A、B、C（示範資料）。','Friends A, B and C (example data).')}}}
function permissionContent(){return `<h2 id="modal-title">${esc(t('讓旅行風格體驗更有你。','Make the travel-style experience yours.'))}</h2><p>${esc(t('選擇讓旅人服務使用哪些資料。可分項選擇，也可全部拒絕。','Choose which data the traveler service may use. Select separately or decline all.'))}</p>${Object.entries(permissionText()).map(([key,p])=>`<label class="permission"><input type="checkbox" data-permission="${key}" ${state.permissions[key]?'checked':''}><span><strong>${esc(p.title)}</strong><span class="muted">${esc(p.desc)}</span></span></label>`).join('')}<div class="actions">${btn('decline-all','全部拒絕並開始','Decline all & start','secondary')}${btn('permissions-next','依目前選擇開始 →','Start with my choices →')}</div>`}
function quiz(){
 if(!instrument.verified)return `<section class="narrow"><h1>${esc(t('體驗暫未開放','The experience is not open yet'))}</h1><p>${esc(t('正式題目正在核對，請稍後再試。','The questionnaire is being verified. Please try again later.'))}</p>${btn('quiz-back','← 返回','← Back','secondary')}</section>`;
 const total=instrument.items.length,n=instrument.items.filter(q=>state.answers[q.id]).length,pages=Math.ceil(total/PAGE_SIZE),start=state.quizPage*PAGE_SIZE;
 return `<section class="narrow"><div class="quiz-top"><div><span class="eyebrow">03 / YOUR TRAVELER STORY</span><h1>${esc(t('你的旅行風格，從這裡開始。','Your travel style starts here.'))}</h1></div><span class="badge">${esc(t(`第 ${state.quizPage+1} / ${pages} 頁`,`Page ${state.quizPage+1} / ${pages}`))}</span></div><div class="meter" role="progressbar" aria-label="${esc(t('作答進度','Response progress'))}" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${n}"><div class="meter-fill" id="quiz-fill"></div></div><p class="muted" id="answer-count"></p><p class="quiz-instructions">${esc(tr(instrument.instructions))}</p><p><strong>${esc(tr(instrument.stem))}</strong></p><div class="panel">${instrument.items.slice(start,start+PAGE_SIZE).map(q=>`<fieldset class="question"><legend><span class="q-number">${esc(t('第','Item'))} ${q.id} ${esc(t('題',''))}</span>${esc(tr(q.text))}</legend><div class="responses tipi-responses">${instrument.responseOptions.map(o=>`<label class="response"><input type="radio" name="q${q.id}" data-question="${q.id}" value="${o.value}" ${state.answers[q.id]===o.value?'checked':''}><span class="value">${o.value}</span><span>${esc(tr(o.label))}</span></label>`).join('')}</div></fieldset>`).join('')}</div><div class="actions quiz-actions">${btn('quiz-back','← 上一步','← Back','secondary')}<span class="muted" id="page-hint"></span>${btn('quiz-next',state.quizPage===pages-1?'看看我的旅人故事 →':'下一頁 →',state.quizPage===pages-1?'See my traveler story →':'Next page →')}</div></section>`
}
function selectedType(){const scores=scoreInstrument(state.answers,instrument);return Object.keys(types).reduce((a,b)=>scores[b].mean>scores[a].mean?b:a)}
function travelerCard(){const c=types[selectedType()];return `<article class="traveler-card"><span class="eyebrow">YOUR TRAVELER STORY</span><div class="card-visual">${travelerImage(c,true)}</div><span class="badge">${esc(t('課堂娛樂詮釋','CLASSROOM ENTERTAINMENT'))}</span><h2>${esc(tr(c.name))}</h2><p>${esc(tr(c.line))}</p><small>${esc(t('一張旅人故事卡，留給今天的想像。','A traveler story card for today’s imagination.'))}</small></article>`}
function result(){return `<section class="narrow"><span class="eyebrow">04 / YOUR STORY, REVEALED</span><h1>${esc(t('你的旅人故事卡，到了。','Your traveler story card is here.'))}</h1>${travelerCard()}<div class="actions">${btn('result-back','← 回看回答','← Review my answers','secondary')}<div class="action-group">${btn('share-preview','預覽分享卡片','Preview the share card','secondary')}${btn('view-platform','看看幕後發生了什麼 →','See what happened behind the scenes →')}</div></div></section>`}
function scoreRows(){const scores=scoreInstrument(state.answers,instrument);return instrument.domains.map(d=>{const s=scores[d.id];return `<div class="score-row"><div class="score-head"><strong>${esc(tr(d.name))}</strong><span class="score">${s.mean.toFixed(2)} / ${instrument.max}</span></div><div class="score-track" aria-hidden="true"><i class="score-fill" data-score-width="${s.mean/instrument.max*100}"></i></div><div class="score-details">${esc(t(`${s.count} 題平均；反向題已轉換`,`${s.count}-item mean; reverse items recoded`))}</div></div>`}).join('')}
function flow(){return `<section class="panel flow-panel"><h2>${esc(t("不知不覺，廠商獲得消費者的資料","Companies obtain consumer data without consumers realizing it"))}</h2><ol class="data-flow" id="data-flow"><li class="flow-node"><span class="badge">01</span><h3>${esc(t("授權選擇","Permission choices"))}</h3><p class="flow-copy">${esc(t("您授權的當下，社群媒體的關係網就被對方掌握","When you authorize access, the other party gains access to your social-media relationship network."))}</p></li><li class="flow-node"><span class="badge">02</span><h3>${esc(t("自填答案","Self-reported answers"))}</h3><p class="flow-copy">${esc(t("選擇旅人類型的答案其實是五大人格特質","Your answers to the traveler-type questions actually describe Big Five personality traits."))}</p></li><li class="flow-node"><span class="badge">03</span><h3>${esc(t("人格推測","Personality estimate"))}</h3><p class="flow-copy">${esc(t("廠商透過五大人格問卷掌握你的人格特質","The company uses a Big Five personality questionnaire to learn about your personality traits."))}</p></li><li class="flow-node reuse"><span class="badge orange">04</span><h3>${esc(t("可能資料再利用","Possible data reuse"))}</h3><p class="flow-copy">${esc(t("基於前述資料，廠商可以進行精準行銷、政治宣傳或詐騙行為。","Based on this information, the company can conduct targeted marketing, political messaging or fraudulent activities."))}</p></li></ol>${btn('replay-flow','播放流程示意','Play the process illustration','secondary')}</section>`}
function reveal(){const p=permissionText();return `<section><span class="eyebrow">05 / BEHIND THE SCENES</span><h1>${esc(t('數據分析師眼中的你：現在，揭露幕後。','The data analyst’s view: time to reveal the mechanism.'))}</h1><p class="lead">${esc(t('剛才的旅行風格問卷，其實使用 TIPI 十題人格量表，概略測量五大人格向度。','The travel-style questionnaire used the ten-item TIPI, a broad measure of the Big Five dimensions.'))}</p>${flow()}<div class="two-col"><div class="panel"><span class="badge">${esc(t('自填資料 · 本人回顧','SELF-REPORT · YOUR OWN REVIEW'))}</span><h2>${esc(t('根據剛剛的旅人類型問題，廠商已經掌握你的人格特質，你的人格特質資料如下：','Based on the traveler-type questions you just answered, the company now knows your personality traits. Your personality-trait data are shown below:'))}</h2>${scoreRows()}<p class="muted">${esc(t('這是本次自填原始平均值，不是常模百分位，不分常模高低、不作臨床診斷，也不決定旅行行為。','These are raw self-report means, not norm percentiles, normative high/low categories or a clinical diagnosis. They do not determine travel behavior.'))}</p><button class="text-button" id="reveal-sources">${esc(t('查看量表來源、使用許可與完整計分','View instrument sources, permission and complete scoring'))}</button></div><div class="panel"><span class="badge">${esc(t('操作紀錄','ACTIVITY RECORDS'))}</span><h2>${esc(t('你實際做的選擇','Your actual choices'))}</h2><ul class="permissions-summary">${Object.entries(p).map(([key,v])=>`<li><span>${esc(v.title)}</span><span class="permission-status">${esc(state.permissions[key]?t('已勾選','Selected'):t('未勾選','Not selected'))}</span></li>`).join('')}</ul><p class="phishing-reflection">${esc(t('如果這是真實的釣魚網站，現在你不僅被企業掌握你的人格特質，還掌握你的社交狀況，企業就可以據以推論你的消費或政治傾向。','If this were a real phishing website, a company would now have not only your personality traits but also information about your social connections, which it could use to infer your consumption preferences or political leanings.'))}</p><p>${esc(state.permissions.answers?t('你允許的是模擬答案使用；資料實際沒有傳出。','You allowed simulated answer use; no data was actually sent.'):t('你未允許模擬平台使用答案。此處仍提供本人的分數回顧。','You did not allow simulated platform use of answers. Your own scores are still available for review.'))}</p></div></div>${answerReview()}<details class="panel"><summary>${esc(t('查看本次操作時間與選擇','Review session times and choices'))}</summary><table class="audit"><thead><tr><th>${esc(t('開始後（秒）','Seconds after start'))}</th><th>${esc(t('操作','Action'))}</th></tr></thead><tbody>${state.events.map(e=>`<tr><td>${(e.ms/1000).toFixed(1)}</td><td>${esc(describeEvent(e))}</td></tr>`).join('')}</tbody></table></details><p class="muted">${esc(t('所有答案與紀錄只在本分頁；教師沒有監控介面。模擬分享只產生本人可見預覽，不發社群或建立公開檔案。重新開始與退出會清除本次資料。','All answers and records stay in this tab; there is no instructor monitoring interface. Simulated sharing creates a preview only, with no social post or public profile. Restart and Exit clear this session.'))}</p><div class="actions">${btn('platform-back','← 返回故事卡','← Back to story card','secondary')}${btn('finish','重新開始並清除本次資料','Restart & clear this session')}</div></section>`}
function answerReview(){return `<details class="panel answer-review"><summary>${esc(t('查看 10 題回答與逐題計分','Review all 10 answers and item scoring'))}</summary><p>${esc(t('反向題採 8 − 原值。例：第 6 題若填 2，計分值為 6；若第 1 題填 5，外向性平均為 (5 + 6) / 2 = 5.5。','Reverse items use 8 − response. For example, item 6 answered 2 scores 6. If item 1 is 5, Extraversion is (5 + 6) / 2 = 5.5.'))}</p>${instrument.items.map(q=>`<div class="score-row"><strong>${q.id}. ${esc(tr(q.text))}</strong><p class="score-details">${esc(tr(instrument.domains.find(d=>d.id===q.domain).name))} · ${esc(q.reverse?t('反向','Reverse'):t('正向','Positive'))}<br>${esc(t('原始回答','Raw response'))}: ${state.answers[q.id]} · ${esc(t('計分值','Scored value'))}: ${q.reverse?8-state.answers[q.id]:state.answers[q.id]}</p></div>`).join('')}</details>`}
function describeEvent(e){const names={notice:t('確認模擬告知','Acknowledged simulation notice'),stage:t('進入階段','Entered stage'),permissionView:t('開啟授權視窗','Opened permission dialog'),permission:t('權限選擇','Permission choice'),declineAll:t('全部拒絕','Declined all'),answer:t('作答','Response'),quizPage:t('問卷頁面','Questionnaire page'),language:t('切換語言','Changed language'),preview:t('開啟分享預覽','Opened share preview')};if(e.type==='permission')return `${names.permission}: ${permissionText()[e.key]?.title||''} / ${e.granted?t('勾選','Selected'):t('取消','Unselected')}`;if(e.type==='answer')return `${names.answer} ${e.item}: ${e.value}`;if(e.type==='language')return `${names.language}: ${e.lang==='zh'?'繁中':'English'}`;if(e.type==='stage')return `${names.stage} ${e.stage}`;if(e.type==='quizPage')return `${names.quizPage} ${e.page+1}`;return names[e.type]||t('本次操作','Session activity')}
function bindStep(){
 if(state.step===1)$('start').onclick=()=>{state.noticeAccepted=true;log('notice');go(2)};
 else if(state.step===2)$('begin-quiz').onclick=()=>openModal('permissions');
 else if(state.step===3){if(!instrument.verified){$('quiz-back').onclick=()=>go(2);return}const renderedPage=state.quizPage;
 const refresh=()=>{const n=instrument.items.filter(q=>state.answers[q.id]).length;$('quiz-fill').style.width=n/instrument.items.length*100+'%';document.querySelector('[role=progressbar]').setAttribute('aria-valuenow',n);$('answer-count').textContent=t(`已回答 ${n} / ${instrument.items.length} 題`,`Answered ${n} / ${instrument.items.length}`);$('quiz-next').disabled=!pageComplete(state.answers,instrument,state.quizPage);$('page-hint').textContent=pageComplete(state.answers,instrument,state.quizPage)?t('本頁完成，可以繼續','Page complete. Continue when ready.'):t('本頁全部作答後繼續','Answer every item on this page to continue')};
 document.querySelectorAll('[data-question]').forEach(el=>el.onchange=()=>{const id=el.dataset.question,value=Number(el.value);if(state.answers[id]!==value){state.answers[id]=value;log('answer',{item:Number(id),value})}refresh()});refresh();
 $('quiz-back').onclick=()=>{if(state.step!==3||state.quizPage!==renderedPage)return;if(state.quizPage===0)go(2);else{state.quizPage--;log('quizPage',{page:state.quizPage});rememberNavigation(true);render(true)}};
 $('quiz-next').onclick=()=>{if(state.step!==3||state.quizPage!==renderedPage||!pageComplete(state.answers,instrument,state.quizPage))return;if(state.quizPage===Math.ceil(instrument.items.length/PAGE_SIZE)-1)go(4);else{state.quizPage++;log('quizPage',{page:state.quizPage});rememberNavigation(true);render(true)}};
 }else if(state.step===4){$('result-back').onclick=()=>go(3);$('share-preview').onclick=()=>{log('preview');openModal('share')};$('view-platform').onclick=()=>go(5)}
 else{$('platform-back').onclick=()=>go(4);$('finish').onclick=clearSession;$('reveal-sources').onclick=()=>openModal('sources');$('replay-flow').onclick=()=>{const el=$('data-flow');el.classList.remove('replaying');void el.offsetWidth;el.classList.add('replaying');$('status').textContent=t('播放概念流程：授權、答案、人格推測、可能資料再利用。','Playing the conceptual process: permissions, answers, personality estimate, possible data reuse.')}}
}
function sourceContent(){return `<h2 id="modal-title">${esc(t('來源、許可與完整計分','Sources, permission & complete scoring'))}</h2><p>${esc(tr(instrument.provenance))}</p><ul class="sources-list">${instrument.sources.map(s=>`<li><strong>${esc(tr(s.title))}</strong><br><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(t('查看原始來源（另開分頁）','View original source (new tab)'))}</a> · <a href="${esc(s.local)}" target="_blank" rel="noopener">${esc(t('本站題項／來源說明檔','Local item / source notes'))}</a></li>`).join('')}</ul><p>${esc(t('作者允許任何人為任何用途使用 TIPI，無需另請求許可；其對譯本的收錄不代表背書，並表示據其所知可自由使用、建議禮貌聯絡譯者。本版不宣稱公有領域、CC 授權或作者認證。','The author permits anyone to use TIPI for any purpose without requesting permission. Listing a translation is not endorsement; translations are free to use as far as he knows, with courtesy contact encouraged. This platform claims no public-domain, Creative Commons or author-certified status.'))}</p><div class="formula">${esc(t('正式 1–7 量尺。反向題 2、4、6、8、10：8 − 原值。E=(1+6R)/2；A=(2R+7)/2；C=(3+8R)/2；ES=(4R+9)/2；O=(5+10R)/2。每個向度 1–7，沒有總分，不補缺答，10 題答完才產生結果。','Original 1–7 scale. Reverse items 2, 4, 6, 8, 10 use 8 − response. E=(1+6R)/2; A=(2R+7)/2; C=(3+8R)/2; ES=(4R+9)/2; O=(5+10R)/2. Each dimension is 1–7. There is no overall total or imputation; all 10 items are required for results.'))}</div><p>${esc(t('ES 是情緒穩定性，較高原始分數表示較高自填穩定性，不能直接稱高神經質。每向度只有兩題，適合概略教學自我探索；不作常模高低、臨床判定或旅行預測。','ES is Emotional Stability; a larger raw score indicates greater self-reported stability, not higher Neuroticism. Two items per dimension give a broad classroom self-exploration measure, without normative cutoffs, clinical decisions or travel predictions.'))}</p><details><summary>${esc(t('原始作答說明（英文）','Original response instructions (English)'))}</summary><p lang="en">Here are a number of personality traits that may or may not apply to you. Please write a number next to each statement to indicate the extent to which you agree or disagree with that statement. You should rate the extent to which the pair of traits applies to you, even if one characteristic applies more strongly than the other.</p></details>`}
function renderModal(){for(const lang of ['zh','en'])$('modal-lang-'+lang).setAttribute('aria-pressed',state.lang===lang);$('modal-close').hidden=modalKind==='permissions';$('modal-content').innerHTML=modalKind==='permissions'?permissionContent():modalKind==='share'?`<h2 id="modal-title">${esc(t('分享卡片預覽','Share card preview'))}</h2>${travelerCard()}<p class="muted">${esc(t('這是本分頁的預覽，沒有貼文被送出。','This preview stays in this tab. No post has been sent.'))}</p>`:sourceContent();if(modalKind==='permissions'){document.querySelectorAll('[data-permission]').forEach(el=>el.onchange=()=>{const key=el.dataset.permission;state.permissions[key]=el.checked;log('permission',{key,granted:el.checked})});$('decline-all').onclick=()=>{for(const k of Object.keys(state.permissions))state.permissions[k]=false;log('declineAll');go(3)};$('permissions-next').onclick=()=>go(3)}}
function openModal(kind,restore=false){if($('modal').open)return;modalKind=kind;modalReturn=document.activeElement?.id;if(kind==='permissions'){state.permissionOpen=true;if(!restore)log('permissionView');save();syncTimer()}renderModal();$('modal').showModal();(kind==='permissions'?$('modal-lang-'+state.lang):$('modal-close')).focus()}
function closeModal(){if(modalKind==='permissions'){flushTimer();state.permissionOpen=false;syncTimer();save()}if($('modal').open)$('modal').close();modalKind=null;if(modalReturn&&$(modalReturn))$(modalReturn).focus()}
$('modal-close').onclick=closeModal;$('modal').addEventListener('cancel',e=>{e.preventDefault();closeModal()});
$('sources-button').onclick=()=>openModal('sources');$('reset').onclick=clearSession;$('exit').onclick=clearSession;
function switchLanguage(lang){if(state.lang===lang)return;flushTimer();state.lang=lang;log('language',{lang});render()}
for(const lang of ['zh','en']){$('lang-'+lang).onclick=()=>switchLanguage(lang);$('modal-lang-'+lang).onclick=()=>switchLanguage(lang)}
document.querySelector('.brand').onclick=e=>{e.preventDefault();go(1)};
document.addEventListener('visibilitychange',syncTimer);window.addEventListener('pagehide',()=>{flushTimer();timerStart=null;save()});window.addEventListener('pageshow',syncTimer);
window.addEventListener('popstate',e=>{if(modalKind)closeModal();flushTimer();const h=e.state;if(h?.lab&&h.generation===state.startedAt){state.step=h.step;state.quizPage=h.page;if(state.step>3&&!isComplete(state.answers,instrument))state.step=3}else state.step=1;state.permissionOpen=false;syncTimer();save();render(true)});
setInterval(()=>{if(timerStart!==null)flushTimer()},1000);save();rememberNavigation();render();if(state.permissionOpen)openModal('permissions',true);syncTimer();
